server:
  port: 8087
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: ip:93000
      cluster-name: my-application
  jackson:
    default-property-inclusion: non_null