server:
  port: 8085

spring:
  profiles:
    active: signle

---
spring:
  profiles: signle
  redis:
    database: 0
    host: 47.96.176.37
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 1000
        min-idle: 1


---
spring:
  profiles: cluster
  redis:
    password:    # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6379
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

---
spring:
  profiles: sentinel
  redis:
    sentinel:
      master: mymaster
    #从节点集合
    nodes: localhost:6379,localhost:6379
    password: root
    timeout: 1000
    jedis:
      pool:
        maxTotal: 1024 #jedis最大分配对象
        maxIdle: 200 #jedis最大保存idel状态对象数
        maxWaitMillis: 10000 #jedis池没有对象返回时，最大等待时间
        testOnBorrow: true
        testOnReturn: true
        blockWhenExhausted: false
        testWhileIdle: true  #Idle时进行连接扫描
        timeBetweenEvictionRunsMillis: 30000 #表示idle object evitor两次扫描之间要sleep的毫秒数
        numTestsPerEvictionRun: 10 #表示idle object evitor每次扫描的最多的对象数
        minEvictableIdleTimeMillis: 60000  #表示一个对象至少停留在idle状态的最短时间，然后才能被idle object evitor扫描并驱逐；这一项只有在timeBetweenEvictionRunsMillis大于0时才有意义
